### ISSUE TITLE
Light dont show in advanced scene

### ISSUE THREAD

**Issue by eonnet** [bphillips09/Control4-HA-Light#1]
I read on the discord channel that advanced scenes functions are not supported yet, but when i add a light via the mobile app after that the light appears in the advanced lightning scenes on composer. But if i try to add it directly from composer you can't.

**Comment by aijayadams** [comment]
It will depend on how advanced your advanced lighting scenes are - but if you're just using them as a collection of "on and off" I've extended BP's driver with support for scenes with simple brightness targets.

This is not a complete or robust implementation as written today - but depending on your use case it might be helpful until there is a more complete implementation of ALS in the driver. 

https://github.com/aijayadams/Control4-HA-Light/tree/advanced_lighting 

<img width="1013" alt="Screenshot 2023-11-26 at 1 07 15 PM" src="https://github.com/bphillips09/Control4-HA-Light/assets/8841026/f9daa9c8-534c-442a-804b-3929d8fd8c57">
