### ISSUE TITLE
Light is missing in Advanced Lighting

### ISSUE THREAD

**Issue by dacorn** [bphillips09/Control4-HA-Light#4]
I was looking to create a lighting scene using the light driver however the HALight is not showing the the menu when adding light loads in the Advanced Lighting in composer. Is there something I need to set up prior to this?

**Comment by bphillips09** [comment]
@dacorn 

Your motion sensors should expose their values in HA as `binary_sensor` for motion and `sensor` for other things like luminance. You can use my [Binary Sensor](https://github.com/bphillips09/Control4-HA-Binary-Sensor) and [Generic Sensor](https://github.com/bphillips09/Control4-HA-generic-Sensor) drivers for these. Anything that has either a string or numerical `sensor` value should work with the Generic Sensor driver. The driver creates three variable types if supported by the entity: String, Integer, and Float. 

If you'd like to support this work:
<a href="https://www.buymeacoffee.com/bphillips09" target="_blank">
<img src="https://cdn.buymeacoffee.com/buttons/v2/default-black.png" alt="Buy Me A Coffee" height="41" width="174"></a>

**Comment by dacorn** [comment]
@bphillips09 I see you made an update to the light code, will you release an new update? Would be great to have the advanced lighting working, looks like that is what you added from the comments. 

I also added the Garage Door opener, however I can't get it working is there any documentation for this one? Thanks as always! Great work on this project.

**Comment by bphillips09** [comment]
@dacorn Is this functionality still missing?

**Comment by dacorn** [comment]
Hi Brandon,

This one is now working fine.

Best Regards,
Dave
